### PR TITLE
refactored whypfs to use boxo as a baseline library

### PR DESCRIPTION
**Pull request by jlogelin**
Migrated whypfs-core to use `boxo` library per [instructions](https://github.com/ipfs/boxo#migrating-to-boxo)

### CODE REVIEW

**Comment by alvin-reyes** [comment]
I did a quick test on this i.e bumping delta to use this branch and I got some errors

```
# github.com/libp2p/go-libp2p-core/network
../../../go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.20.1/network/rcmgr.go:166:27: network.NullResourceManager (type) is not an expression
# github.com/libp2p/go-libp2p-core/host
../../../go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.20.1/host/host.go:23:32: undefined: host.IntrospectableHost
# github.com/libp2p/go-libp2p-pubsub
../../../go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/pubsub.go:326:32: cannot use ps.protoMatchFunc(string(id)) (value of type func(string) bool) as type func(protocol.ID) bool in argument to h.SetStreamHandlerMatch
make: *** [build] Error 2
```

it's the same error when I tested this unix fs bump https://github.com/application-research/delta/pull/54/files

I need to investigate why and how to fix it on Delta first.

**Comment by jlogelin** [comment]
@alvin-reyes this is strange, not seeing it on my side - did you do a `go mod tidy` first?

**Comment by alvin-reyes** [comment]
All good now. 

FYI: I'm removing the examples folder and putting them into another branch. The examples are importing different libraries that are not necessary to whypfs-core.

**Review by alvin-reyes — COMMENTED** [review]
LGTM

**Pull request merged**
